# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
cache:
 - duration: none
final_space: true
patch_pwsh_bleed: true
shell_integration: true
enable_cursor_positioning: true
iterm_features: false
upgrade:
  - notice: true
  - interval: 168h
  - auto: true
  - source: cdn
version: 3
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: powerline
        powerline_symbol: "î‚°"
        foreground: "#ffffff"
        background: "#d50000"
        properties:
          style: folder
