final_space: true
version: 3
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: powerline
        powerline_symbol: "î‚°"
        foreground: "#ffffff"
        background: "#d50000"
        properties:
          style: folder
