cache:
 - duration: none
final_space: true
patch_pwsh_bleed: true
shell_integration: true
enable_cursor_positioning: true
upgrade:
  notice: true
  interval: 168h
  auto: false
  source: cdn
version: 3
blocks:
 type: git
 style: powerline
 powerline_symbol: î‚°
 foreground: "#193549"
 background: "#ffeb3b"
 background_templates:
   - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}"
   - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}"
   - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
   - "{{ if gt .Behind 0 }}#B388FB{{ end }}"
 template: "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus
   }}{{ end }}{{ if .Working.Changed }} ï„ {{ .Working.String }}{{ end }}{{ if and
   (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ï†
   {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} ïƒ‡ {{ .StashCount }}{{
   end }}"
 properties:
   fetch_status: true
   fetch_upstream_icon: true
   untracked_modes:
     /Users/user/Projects/oh-my-posh/: no
   source: cli
   mapped_branches:
     feat/*: "ğŸš€ "
     bug/*: "ğŸ› "
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: powerline
        powerline_symbol: "î‚°"
        foreground: "#ffffff"
        background: "#d50000"
        properties:
          style: folder
        
